"""``uv run orimera-corpus``: write the corpus and the ground truth that goes with it.

The manifest is written from the same plan that drew the pixels, in the same run, and it records
the SHA-256 of the bytes on disk. That last part is what makes it useful rather than decorative:
the digest is the blob key ingest will compute, so a later evaluation can join its ground truth
to a stored capture through the content address rather than through a filename, and a filename
is exactly the kind of thing invariant 1 refuses to let an evidence address depend on.

Re-running is safe and is meant to be normal. The same seed produces byte-identical files, so a
second run rewrites the same bytes and a subsequent ingest recomputes nothing and bills nothing.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

from orimera.corpus.photograph import (
    GENERATOR_SOFTWARE,
    SYNTHETIC_DESCRIPTION,
    compose,
    encode_jpeg,
)
from orimera.corpus.plan import DEVICES, TRIPS, FramePlan, build_plan
from orimera.corpus.world import PLACES, SUBJECT_LABELS, SUBJECTS

__all__ = ["main"]

_DEFAULT_OUT = Path(".orimera/media/intake/synthetic")

_README = """# Synthetic corpus

Generated by `uv run orimera-corpus`. Every file here is a rendered geometric arrangement, not a
photograph. The device names, the coordinates and the times are fabricated and each frame says so
in its own EXIF `ImageDescription`, `Make`, `Model` and `Software`.

`MANIFEST.json` is the ground truth: for every frame, the camera pose it was drawn from, the
instant it claims, the position it claims, and the SHA-256 of the bytes. The digest is the blob
key ingest computes, so an evaluation joins to a stored capture by content address rather than by
filename.

Delete this directory and re-run the generator to rebuild it. The same seed produces the same
bytes, so a rebuild followed by an ingest recomputes nothing.

This is not the real corpus. It exercises the pipeline; it does not stand in for somebody's life.
"""


def _frame_record(frame: FramePlan, digest: str, byte_size: int) -> dict[str, Any]:
    """One frame's ground truth. Every value here is what was intended, never what was read back.

    The point of a ground truth is that it was not derived from the artefact it is used to score,
    so nothing in this record is parsed out of the file that was just written.
    """
    device = DEVICES[frame.device_key]
    return {
        "filename": frame.filename,
        "sha256": digest,
        "byte_size": byte_size,
        "trip": frame.trip_key,
        "place": frame.place_key,
        "ordinal": frame.ordinal,
        "device": {"key": device.key, "make": device.make, "model": device.model},
        "camera": {
            "eye": list(frame.camera.eye),
            "target": list(frame.camera.target),
            "horizontal_fov_degrees": frame.camera.horizontal_fov_degrees,
        },
        "display_size": list(frame.display_size),
        "exif_orientation": frame.exif_orientation,
        "local_time": frame.local_time.isoformat(),
        "written_utc_offset": (
            None if frame.written_offset is None else _offset_text(frame.written_offset)
        ),
        "utc_instant": frame.utc_instant.isoformat(),
        # Stated separately from `written_utc_offset` because the file not saying its offset is a
        # fact about the file, and the true instant being known anyway is a fact about the plan.
        # An evaluation that conflated them would score the pipeline for guessing correctly.
        "instant_is_recoverable_from_the_file": frame.written_offset is not None
        or (frame.gps_e7 is not None and DEVICES[frame.device_key].writes_offset),
        "gps_e7": None if frame.gps_e7 is None else list(frame.gps_e7),
        "altitude_mm": frame.altitude_mm,
        "subjects": [key for key, _position, _yaw in frame.subject_placements],
    }


def _offset_text(offset: dt.timedelta) -> str:
    total = int(offset.total_seconds() // 60)
    sign = "+" if total >= 0 else "-"
    hours, minutes = divmod(abs(total), 60)
    return f"{sign}{hours:02d}:{minutes:02d}"


def _write(out: Path, seed: int, frames_per_trip: int, stream: Any) -> int:
    frames = build_plan(seed=seed, frames_per_trip=frames_per_trip)
    out.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, Any]] = []

    for index, frame in enumerate(frames, start=1):
        data = encode_jpeg(frame, compose(frame))
        (out / frame.filename).write_bytes(data)
        records.append(_frame_record(frame, hashlib.sha256(data).hexdigest(), len(data)))
        print(
            f"  [{index:>3}/{len(frames)}] {frame.filename:32s} "
            f"{frame.display_size[0]}x{frame.display_size[1]} "
            f"orientation {frame.exif_orientation}  {len(data) // 1024} KiB",
            file=stream,
        )

    manifest = {
        "generator": GENERATOR_SOFTWARE,
        "synthetic": True,
        "disclosure": SYNTHETIC_DESCRIPTION,
        "seed": seed,
        "frames_per_trip": frames_per_trip,
        "subjects": SUBJECTS,
        # The one entry in this document that is a guess rather than a fact the generator
        # produced. See SUBJECT_LABELS in orimera/corpus/world.py for what that means and for
        # why an unresolvable mapping blocks M6 rather than scoring it zero.
        "subject_labels": {key: list(labels) for key, labels in SUBJECT_LABELS.items()},
        "places": {key: place.label for key, place in PLACES.items()},
        "trips": [
            {
                "key": trip.key,
                "place": trip.place_key,
                "device": trip.device_key,
                "subjects": list(trip.subjects),
                "has_gps": trip.gps_centroid_e7 is not None,
            }
            for trip in TRIPS
        ],
        "frames": records,
    }
    (out / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (out / "README.md").write_text(_README, encoding="utf-8")
    print(f"\nwrote {len(records)} frames and MANIFEST.json to {out}", file=stream)
    return 0


def main(argv: list[str] | None = None, stream: Any = None) -> int:
    stream = stream or sys.stdout
    parser = argparse.ArgumentParser(prog="orimera-corpus", description=__doc__)
    parser.add_argument("--out", default=str(_DEFAULT_OUT))
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument(
        "--frames-per-trip",
        type=int,
        default=16,
        help="frames per visit. Five visits, so the corpus is five times this.",
    )
    args = parser.parse_args(argv)
    return _write(Path(args.out), args.seed, args.frames_per_trip, stream)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
