"""One frame plan becomes one JPEG that a camera could plausibly have written.

Two things happen here that are easy to get wrong and that the rest of the pipeline depends on.

**The pixels are written in sensor space, not display space.** A phone stores the sensor readout
unrotated and records how to display it in one EXIF tag, which is why
`orimera/ingest/exif.py` exists at all. A corpus that wrote upright pixels and then tagged them
`Orientation = 6` would not be a corpus of rotated photographs; it would be a corpus of correctly
oriented photographs that ingest then turns sideways. So the renderer draws the picture the right
way up, and this module applies the INVERSE of the display transform before encoding. Ingest then
applies the forward transform and gets the original back, which is exactly what happens to a real
photograph and is what `tests/test_synthetic_corpus.py` asserts.

The inverse is taken from Pillow's own transpose operations rather than derived, because four of
the eight orientations include a mirror and composing a mirror with a rotation in the wrong order
is a silent quarter-turn error. Every entry below is either an involution or one half of an
explicit inverse pair, and the test proves the round trip for all eight rather than for the ones
somebody thought to check.

**The file says it is synthetic, in its own bytes.** `Make`, `Model`, `Software` and
`ImageDescription` all name this generator. A synthetic frame that escaped the corpus directory
would still be recognisable as synthetic from the file alone, which is the only place that
guarantee can live: a directory name is not part of the photograph.
"""

from __future__ import annotations

import io
import random
from typing import Final

from PIL import Image
from PIL.TiffImagePlugin import IFDRational

from orimera.corpus.plan import DEVICES, FramePlan
from orimera.corpus.render import Face, Light, render
from orimera.corpus.world import PLACES, SUBJECT_BUILDERS

__all__ = [
    "GENERATOR_SOFTWARE",
    "SYNTHETIC_DESCRIPTION",
    "TO_SENSOR_TRANSPOSE",
    "compose",
    "encode_jpeg",
]

GENERATOR_SOFTWARE: Final = "orimera-corpus 1"

SYNTHETIC_DESCRIPTION: Final = (
    "Synthetic frame generated by orimera-corpus. Rendered from a geometric arrangement. "
    "Not a photograph of anywhere real and not a record of any real device, time or position."
)

#: Display to sensor. The inverse of what `PIL.ImageOps.exif_transpose` applies for each value.
#: Orientation 1 is absent because it is the identity and the caller skips it.
#:
#: THE ONLY COPY. `tests/conftest.py` writes sensor-space photographs for the ingest tests and
#: imports this rather than keeping its own table. Two tables would be two places for the four
#: mirrored entries to drift, and a drift there produces citations placed on the wrong side of a
#: flipped image, which `docs/domain-and-evidence-model.md` 1.5 records as baked permanently into
#: a span digest.
TO_SENSOR_TRANSPOSE: Final[dict[int, int]] = {
    2: Image.Transpose.FLIP_LEFT_RIGHT,
    3: Image.Transpose.ROTATE_180,
    4: Image.Transpose.FLIP_TOP_BOTTOM,
    5: Image.Transpose.TRANSPOSE,
    6: Image.Transpose.ROTATE_90,
    7: Image.Transpose.TRANSVERSE,
    8: Image.Transpose.ROTATE_270,
}

_EXIF_IFD: Final = 0x8769
_GPS_IFD: Final = 0x8825

_GRAIN_TILE: Final = 160 * 120


def faces_for(frame: FramePlan) -> list[Face]:
    """The place, plus whatever was being carried on this visit.

    The subjects are appended rather than merged into the place, because the same place with
    different objects in it is the whole cross-capture continuity question and keeping them
    separable here is what lets the manifest state which was which.
    """
    place = PLACES[frame.place_key]
    faces = list(place.faces)
    for key, position, yaw in frame.subject_placements:
        faces.extend(SUBJECT_BUILDERS[key](position, yaw))
    return faces


def compose(frame: FramePlan) -> Image.Image:
    """Render the picture the right way up. Sensor-space rotation happens in `encode_jpeg`."""
    place = PLACES[frame.place_key]
    rng = random.Random(frame.grain_seed)
    grain = [min(255, max(0, round(rng.gauss(128.0, 26.0)))) for _ in range(_GRAIN_TILE)]
    return render(
        faces_for(frame),
        frame.camera,
        Light(
            direction=place.light_direction,
            ambient=0.42 if place.indoors else 0.28,
            fill_direction=place.fill_direction,
            fill_weight=place.fill_weight,
        ),
        sky_top=place.sky_top,
        sky_bottom=place.sky_bottom,
        grain_values=grain,
    )


def _rational_dms(value_e7: int) -> tuple[IFDRational, IFDRational, IFDRational]:
    """Signed ten-millionths of a degree to an exact EXIF degrees/minutes/seconds triple.

    Exact rather than rounded: the seconds component keeps a denominator of ten million, so
    reading the triple back through `orimera.ingest.exif` reproduces the original integer with no
    drift. A corpus whose recorded position differed from its stated position by a rounding step
    would make every clustering radius slightly untrue.
    """
    magnitude = abs(value_e7)
    degrees, remainder = divmod(magnitude, 10_000_000)
    minutes, sub_minute = divmod(remainder * 60, 10_000_000)
    return (
        IFDRational(degrees, 1),
        IFDRational(minutes, 1),
        IFDRational(sub_minute * 60, 10_000_000),
    )


def _exif_for(frame: FramePlan) -> Image.Exif:
    device = DEVICES[frame.device_key]
    exif = Image.Exif()
    exif[0x010F] = device.make
    exif[0x0110] = device.model
    exif[0x0131] = GENERATOR_SOFTWARE
    exif[0x010E] = SYNTHETIC_DESCRIPTION
    exif[0x0112] = frame.exif_orientation
    stamp = frame.local_time.strftime("%Y:%m:%d %H:%M:%S")
    exif[0x0132] = stamp

    ifd = exif.get_ifd(_EXIF_IFD)
    ifd[0x9003] = stamp
    ifd[0x9004] = stamp
    if frame.written_offset is not None:
        total_minutes = int(frame.written_offset.total_seconds() // 60)
        sign = "+" if total_minutes >= 0 else "-"
        hours, minutes = divmod(abs(total_minutes), 60)
        ifd[0x9011] = f"{sign}{hours:02d}:{minutes:02d}"
        ifd[0x9010] = ifd[0x9011]
    if frame.subsecond is not None:
        ifd[0x9291] = f"{frame.subsecond:02d}"

    if frame.gps_e7 is not None:
        gps = exif.get_ifd(_GPS_IFD)
        latitude, longitude = frame.gps_e7
        gps[1] = "N" if latitude >= 0 else "S"
        gps[2] = _rational_dms(latitude)
        gps[3] = "E" if longitude >= 0 else "W"
        gps[4] = _rational_dms(longitude)
        if frame.altitude_mm is not None:
            gps[5] = 0 if frame.altitude_mm >= 0 else 1
            gps[6] = IFDRational(abs(frame.altitude_mm), 1000)
        # GPS time is written only by the device that has a fix it trusts. The other device
        # records a position and no time, which is a real and common combination and the one
        # that leaves the instant unknown within an unrecorded UTC offset.
        if DEVICES[frame.device_key].writes_offset:
            instant = frame.utc_instant
            gps[29] = instant.strftime("%Y:%m:%d")
            gps[7] = (
                IFDRational(instant.hour, 1),
                IFDRational(instant.minute, 1),
                IFDRational(instant.second, 1),
            )
    return exif


def encode_jpeg(frame: FramePlan, display: Image.Image, *, quality: int = 88) -> bytes:
    """Sensor pixels plus the tag that uprights them, as the bytes a camera would have written."""
    sensor = display
    operation = TO_SENSOR_TRANSPOSE.get(frame.exif_orientation)
    if operation is not None:
        sensor = display.transpose(operation)
    buffer = io.BytesIO()
    sensor.save(
        buffer,
        format="JPEG",
        quality=quality,
        subsampling="4:2:0",
        exif=_exif_for(frame).tobytes(),
        optimize=True,
    )
    return buffer.getvalue()
