"""Protected topology, reviewed styles, immutable versions, and source availability."""

from exulanica.world.errors import (
    InvalidInteractionData,
    InvalidInteractionPreviewState,
    InvalidPreviewState,
    InvalidStructuralData,
    InvalidStructuralPreviewState,
    InvalidStyleData,
    ProtectedTopologyConflict,
    StaleInteractionPolicy,
    StaleStructuralBase,
    StaleStyleVersion,
    UnavailableAsset,
    UnknownWorldResource,
    WorldNotConfigured,
)
from exulanica.world.interaction import (
    INTERACTION_POLICY_REGISTRY,
    InteractionPolicyRegistry,
    InteractionPolicyState,
    InteractionPolicyVersion,
    InteractionPreview,
    InteractionProposal,
    InteractionProposalRecord,
    InteractionRecommendation,
)
from exulanica.world.interaction_repository import WorldInteractionPolicyRepository
from exulanica.world.models import (
    DEFAULT_WORLD_ID,
    ProposalOrigin,
    ProposalProvenance,
    SourceMediaState,
    StylePreview,
    StyleProposal,
    StyleProposalRecord,
    StyleReference,
    StyleScope,
    StyleVersion,
    TopologyContract,
    TopologySourceSlot,
    WorldSourceMedia,
)
from exulanica.world.registry import STYLE_REGISTRY, StyleRegistry
from exulanica.world.repository import WorldStyleRepository
from exulanica.world.structure import (
    PlacementMigration,
    SpatialCandidate,
    SpatialDigests,
    SpatialPreview,
    SpatialSnapshot,
)
from exulanica.world.structure_repository import WorldStructureRepository

__all__ = [
    "DEFAULT_WORLD_ID",
    "INTERACTION_POLICY_REGISTRY",
    "STYLE_REGISTRY",
    "InteractionPolicyRegistry",
    "InteractionPolicyState",
    "InteractionPolicyVersion",
    "InteractionPreview",
    "InteractionProposal",
    "InteractionProposalRecord",
    "InteractionRecommendation",
    "InvalidInteractionData",
    "InvalidInteractionPreviewState",
    "InvalidPreviewState",
    "InvalidStructuralData",
    "InvalidStructuralPreviewState",
    "InvalidStyleData",
    "PlacementMigration",
    "ProposalOrigin",
    "ProposalProvenance",
    "ProtectedTopologyConflict",
    "SourceMediaState",
    "SpatialCandidate",
    "SpatialDigests",
    "SpatialPreview",
    "SpatialSnapshot",
    "StaleInteractionPolicy",
    "StaleStructuralBase",
    "StaleStyleVersion",
    "StylePreview",
    "StyleProposal",
    "StyleProposalRecord",
    "StyleReference",
    "StyleRegistry",
    "StyleScope",
    "StyleVersion",
    "TopologyContract",
    "TopologySourceSlot",
    "UnavailableAsset",
    "UnknownWorldResource",
    "WorldInteractionPolicyRepository",
    "WorldNotConfigured",
    "WorldSourceMedia",
    "WorldStructureRepository",
    "WorldStyleRepository",
]
